### PR TITLE
Add vue language support

### PR DESCRIPTION
**Pull request by vikingair**
Not sure if I missed something as the test results were not really helpful to me. I was not able to find contribution guidelines or code documentation.

### CODE REVIEW

**Comment by ChuYang-FE** [comment]
Bruh, I'd like to contribute to this by adding a PR just like yours, but it appears that the repository is no longer actively maintained. That's insane... 🤬

**Comment by fdc-viktor-luft** [comment]
I've written a direct mail to @conorhastings. Hope it helps :)

**Comment by fdc-viktor-luft** [comment]
@conorhastings Never replied to my mail. Maybe @simmerer can help? Is this repo effectively dead?

**Comment by simmerer** [comment]
`15.6.0` just went out. https://www.npmjs.com/package/react-syntax-highlighter?activeTab=versions

**Pull request merged**
