### PR TITLE
Pass customStyles and className even if useInlineStyles is false

### PR DESCRIPTION
**Pull request by prichey**
Fixes https://github.com/conorhastings/react-syntax-highlighter/issues/278

### CODE REVIEW

**Comment by prichey** [comment]
Looks like there were some unrelated snapshots that got pruned whenever I ran `npm test -- -u`. If those should be reverted I can remove.

**Comment by simmerer** [comment]
Thanks for contributing this, @prichey! Taking a look now.

**Comment by simmerer** [comment]
Fix looks good, @prichey !

You're right, if you revert the changes to these three files:
- `__tests__/__snapshots__/prism-async-light.js.snap`
- `__tests__/__snapshots__/async-light.js.snap`
- `package.json`

we'll be conflict-free and ready to merge.

**Comment by prichey** [comment]
Sounds good, I'll revert 👍

**Comment by prichey** [comment]
@simmerer done!

**Pull request merged**
